<article class="font-white" style="background-color: rgb(0, 0, 0); background-image: url(/page/image/skills.png); background-position: center center; background-size: cover; box-shadow: 0px 0px 150px 30px rgb(0, 0, 0) inset">
    <div class="table center font-white">
        <div class="avatar" style="vertical-align: middle">
            <img src="/public/image/photo.png" alt="Чернов Александр">
        </div>
        <div style="vertical-align: middle">
            <h1>
               Чернов Александр
            </h1>
            <address>
                Росиия, Белгородская область, г. Старый Оскол
            </address>
            <p>
                Программист. Люблю работать с <a>C#</a>, <a>C++</a>, <a>PHP</a>, <a>Node.js</a>
            </p>
        </div>
    </div>
</article>
<article class="center font-white">
    <div>
    <h2>
        Образование
    </h2>
    </div>
    <p>
        Закончил в 2011 году Восточноукраинский Национальный Университет им. В. Даля получив полное высшее образование по специальности «Информационные управляющие системы и технологии» и квалификацию инженера компьютерных систем. Дипломная работа на тему «Разработка информационной системы “Социальная сеть“. Разработка элементов системы управления учебным процессом ВНУ с использованием социальных сетей» защищена с отметкой отлично.
    </p>
    <p>
        Закончил в 2010 году Восточноукраинский Национальный Университет им. В. Даля получив базовое высшее образование по направлению «Компьютерные науки» и квалификацию бакалавра техника-программиста. Дипломная работа на тему «Информационная система поддержки учебного процесса для автошколы “Дом Авто”» защищена с отметкой отлично, внедрена и на данный момент используется.
    </p>
    <p>
        Закончил в 2007 году колледж Восточноукраинского Национального Университета им. В. Даля по специальности «Обслуживание компьютерных и интеллектуальных систем и сетей» получив квалификацию техника-электронщика. 
    </p>
</article>
<article class="center emphasis">
    <div>
        <div>C++, C#, ASP.NET, WPF, Silverlight, JavaScript, jQuery, PHP, MySQL, SQL, MVC, Node.js, MongoDB, HTML5, CSS3, SEO, SMO, API, Microsoft WebMatrix, Miscrosoft Visual Studio</div>
    </div>
</article>