<article class="font-white" style="background-color: rgb(0, 0, 0); background-image: url(/page/image/skills.png); background-position: center center; background-size: cover; box-shadow: 0px 0px 150px 30px rgb(0, 0, 0) inset">
    <div class="table center font-white font-light">
        <h1>
            Simple PHP MVC Engine
        </h1>
    </div>
</article>
<article class="center font-white">
    <div>
    <h2 class="font-light">
        AeonRush <?php new Test('index', $this); ?>
    </h2>
    </div>
</article>
<article class="center emphasis">
    <div>
        <div>/// Something</div>
    </div>
</article>