<article class="logo">
    <div class="font-white">
        <h1>
            Simple PHP MVC Engine
        </h1>
    </div>
</article>
<article>
    <div>
    <h2 class="font-light">
        <?php new \Fragment\Home('index', $this, 'Simple, stylish, fast!'); ?>
        <?php new \Fragment\Home('index', $this, 'Modern, progressive!'); ?>
        <?php new \Fragment\Home('index', $this, 'Eva'); ?>
    </h2>
    </div>
</article>
