<!DOCTYPE html>
<html lang="<?php echo $this->lang ?>">
<head>
	<link rel="shortcut icon" href="/public/image/favicon.ico">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!---
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
-->
	<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<!--- Каноническая ссылка -->
	<?php if(isset($this->canonical{6})) { ?> <link rel="canonical" href="<?php echo $this->canonical?>"> <?php } ?>
	<title><?php echo $this->title?></title>
	<!--- Ключевые слова -->
	<?php if(isset($this->keywords{16})) { ?> <meta name="keywords" content="<?php echo $this->keywords?>"> <?php } ?>
	<!--- Описание страницы -->
	<?php if(isset($this->description{8})) { ?> <meta name="description" content="<?php echo $this->description?>"> <?php } ?>

	<meta name="generator" content="AEON Web Engine">
	<?php if(sizeof($this['meta']) > 0) echo join ('', $this['meta']); ?>

    <!--- Styles -->
    <link rel="stylesheet" href="/layout/default/default.css">
    <style>
        @font-face {
            font-family: 'Neo Sans';
            src: url('/public/font/NeoSansPro-Regular.woff') format('woff'), url('/public/font/NeoSansPro-Regular.ttf') format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'Neo Sans Light';
            src: url('/public/font/NeoSansPro-Light.woff') format('woff'), url('/public/font/NeoSansPro-Light.ttf') format('truetype');
            font-weight: lighter;
            font-style: normal;
        }
        @font-face {
            font-family: 'UnSeen';
            src: url('/public/font/unseen.woff') format('woff'), url('/public/font/unseen.ttf') format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'Helvetica Ultra Light';
            src: url('/public/font/helvetica-neue-ultra-light.woff') format('woff'), url('/public/font/helvetica-neue-ultra-light.ttf') format('truetype');
            font-weight: lighter;
            font-style: normal;
        }
    </style>

</head>
<body>
<!--- Header section -->
<header>
	<!--- Menu -->
    <nav>
        <a><img src="/layout/default/image/menu10.svg" alt="Menu" onclick="$('header > nav:last-child').toggleClass('show')"></a>
    </nav>
	<nav>
        <a href="/" id="home">Home</a>
	</nav>
</header>
<!--- Content section -->
<?php echo $this->content?>
<section class="font-white font-light social-share">
    <article>
        <div>
            <h2>Будьте на связи</h2>
            <nav>
                <a><img src="/layout/default/image/facebook42.svg" alt="Facebook"><span>Facebook</span></a>
                <a><img src="/layout/default/image/vkcom1.svg" alt="VK"><span>VK</span></a>
            </nav>
        </div>
    </article>
</section>
<!--- Footer section -->
<footer>
	<div>
		&copy; <?php echo Date('Y')?><a href="http://aeonrush.com/">AeonRush</a>
        <select onchange="location = '/' + this.value.toLowerCase() + location.pathname.substr(6)">
            <?php $c = \app::local()->getCurrentLanguage(); foreach(\app::local()->getSupportedLanguages() as $k => $v) { ?>
                <option value="<?php echo $k?>" <?php if($c == $k) echo "selected"?>><?php echo $v['language-name']?></option>
            <?php }; ?>
        </select>
	</div>
</footer>

<!--- Styles -->
<?php  $j = sizeof($this['css']['src']); for($i=0;$i<$j; ++$i) { ?><link rel="stylesheet" href="<?php echo $this['css']['src'][$i]?>"><?php } ?>
<?php if(sizeof($this['css']['inline']) > 0) { ?><style><?php echo join ('', $this['css']['inline'])?></style><?php } ?>

<!--- JavaScript -->
<script src="/public/javascript/jquery-2.1.1.min.js"></script>
<?php  $j = sizeof($this['javascript']['src']); for($i=0;$i<$j; ++$i) { ?><script src="<?php echo $this['javascript']['src'][$i]?>"></script><?php } ?>
<?php if(sizeof($this['javascript']['inline']) > 0) { ?><script><?php echo join ('', $this['javascript']['inline'])?></script><?php } ?>
</body>
</html>